export const emptyProduct: Product = {
  itemId: 0,
  itemName: "",
  price: 0,
  itemDetail: "",
  itemSellStatus: "",
  regTime: "",
  memberNickName: "",
  stockNumber: 0,
  sellPlace: "",
  itemReserver: null,
  itemRamount: 0,
  itemImgList: [],
  itemSeller: 0,
  boardDTOList: [],
};
